apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-cloud-setup
  namespace: flux-system
spec:
  interval: 1m
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: monitoring-cloud
  path: ./_setup
  prune: true
  force: true
