# if clusterPurpose is esm, then create a prometheus rule for flux components
{{- if eq .Values.clusterPurpose "esm" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-prometheus-stack-fluxops.rules
spec:
  groups:
  - name: fluxops.rules
    rules:
    - expr: |-
        sum by (name) (gotk_reconcile_condition{type="Ready",status="False",kind=~"Kustomization"} > 0) > 0
      record: fluxops_reconcile_condition:kustomization_not_ready
    - expr: |-
        sum by (name) (gotk_reconcile_condition{type="Ready",status="False",kind=~"HelmRelease"} > 0) > 0
      record: fluxops_reconcile_condition:helmrelease_not_ready
    - expr: |-
        sum by (name) (gotk_reconcile_condition{type="Ready",status="False",kind=~"GitRepository|HelmRepository|Bucket"} > 0) > 0
      record: fluxops_reconcile_condition:source_not_ready
    - expr: |-
        sum by (kind, name) (gotk_suspend_status > 0) > 0
      record: fluxops_resources_suspended:count
{{ end }}
